### ISSUE TITLE
Aruba 8.7.1.5

### ISSUE THREAD

**Issue by pwong-splunk** [pysnmp/mibs#11]
Is it possible to have different version of MIBs from the same vendor please? 

Controller:
[aruba-mibs_8.7.1.5_81372.tar.gz](https://github.com/pysnmp/mibs/files/8609630/aruba-mibs_8.7.1.5_81372.tar.gz)
[standard-mibs_8.7.1.5_81372.tar.gz](https://github.com/pysnmp/mibs/files/8609633/standard-mibs_8.7.1.5_81372.tar.gz)

**Comment by pwong-splunk** [comment]
AP:
[aruba-mibs_8.7.1.5_81372-AP.tar.gz](https://github.com/pysnmp/mibs/files/8609655/aruba-mibs_8.7.1.5_81372-AP.tar.gz)
[standard-mibs_8.7.1.5_81372-AP.tar.gz](https://github.com/pysnmp/mibs/files/8609657/standard-mibs_8.7.1.5_81372-AP.tar.gz)

**Comment by pwong-splunk** [comment]
AP:
[aruba-mibs_8.7.1.5_81372-AP.tar.gz](https://github.com/pysnmp/mibs/files/8609673/aruba-mibs_8.7.1.5_81372-AP.tar.gz)
[standard-mibs_8.7.1.5_81372-AP.tar.gz](https://github.com/pysnmp/mibs/files/8609674/standard-mibs_8.7.1.5_81372-AP.tar.gz)

**Comment by omrozowicz-splunk** [comment]
Hello!
Could you please tell me why you need the lower version of a MIB file? Because they should be backward compatible and we have >  8.8 version here. Is any specific query in SC4SNMP that doesn't translate correctly for you for Aruba MIB?

**Comment by pwong-splunk** [comment]
As long as they are backward compatible.  In that case, I will try it with the current version first.  Thanks for your help.
