### ISSUE TITLE
PlugPower MIB

### ISSUE THREAD

**Issue by olgaktoronto** [pysnmp/mibs#134]
HFC | PLUG POWER | E-2500

- MIB module for Plug Power products        REVISION "201603030000Z" -- March 3,2016        DESCRIPTION  "Seventh version."        -- 1.3.6.1.4.1.17022 --

[PlugPower_ESeries_V01_01_02.zip](https://github.com/user-attachments/files/15957184/PlugPower_ESeries_V01_01_02.zip)
[PlugPower_ESeries_V01_01_02.zip](https://github.com/user-attachments/files/15957184/PlugPower_ESeries_V01_01_02.zip)
ALT-DEL MIB 

- ORGANIZATION "www.altergy.com" DESCRIPTION  "MIB objects for Altergy fuel cell and reformer"

[ALT-DEV_2020-02-12.zip](https://github.com/user-attachments/files/15991187/ALT-DEV_2020-02-12.zip)
ALARM-MIB

- The MIB module describes a generic solution to model alarms and to store the current list of active alarms.

 The   initial version of this MIB module was published   in RFC 3877.  Supplementary information may be available on:            http://www.ietf.org/copyrights/ianamib.html"  DESCRIPTION       "Initial version, published as RFC 3877."
[ALARM-MIB.zip](https://github.com/user-attachments/files/15991189/ALARM-MIB.zip)
ALPHA-CONVERTER-SYS-MIB

- ORGANIZATION "Alpha Technologies Ltd." DESCRIPTION  "This MIB defines the notification block(s) available in system controllers."

[ALPHA-CONVERTER-SYS-MIB.zip](https://github.com/user-attachments/files/15991210/ALPHA-CONVERTER-SYS-MIB.zip)
ALPHA-NOTIFICATION-MIB 

- ORGANIZATION "Alpha Technologies Ltd." DESCRIPTION  "This MIB defines the notification block(s) available in system controllers."

[ALPHA-NOTIFICATION-MIB.zip](https://github.com/user-attachments/files/16072421/ALPHA-NOTIFICATION-MIB.zip)

ALPHA-RECTIFIER-SYS-MIB 

- ORGANIZATION "Alpha Technologies Ltd." DESCRIPTION 	"This MIB defines the notification block(s) available in system controllers."

[ALPHA-RECTIFIER-SYS-MIB.zip](https://github.com/user-attachments/files/15991261/ALPHA-RECTIFIER-SYS-MIB.zip)
ALPHA-RESOURCE-MIB 

- ORGANIZATION "Alpha Technologies Ltd." 	DESCRIPTION 	"This MIB defines the information block(s) available in system controllers."         

[ALPHA-RESOURCE-MIB.zip](https://github.com/user-attachments/files/15991291/ALPHA-RESOURCE-MIB.zip)

**Comment by ajasnosz** [comment]
Hello Olga, I've added the Plugpower mib to our server, but as you mentioned few more mibs that you would like to add, we will wait with release of new version until then. If you expect that collecting them would take more time, let us know and we will release new version with this mib only.

**Comment by olgaktoronto** [comment]
hi Agnieszka, thank you so much! I have all the MIBs , I just had no time to add them! Give me one day please, and they all will be there

**Comment by olgaktoronto** [comment]
ALT-DEV MIB
[ALT-DEV_2020-02-12.zip](https://github.com/user-attachments/files/15991145/ALT-DEV_2020-02-12.zip)

**Comment by olgaktoronto** [comment]
ALARM-MIB
[ALARM-MIB.zip](https://github.com/user-attachments/files/15991160/ALARM-MIB.zip)

**Comment by olgaktoronto** [comment]
hi @ajasnosz - I have added all MIBs not found in index.csv. Thank you!

**Comment by ajasnosz** [comment]
Hello @olgaktoronto, I see you added the ALPHA-CONVERTER-SYS-MIB.zip twice instead of ALPHA-NOTIFICATION-MIB.

**Comment by olgaktoronto** [comment]
Hi @ajasnosz ,  sorry, my mistake, thanks for noticing! Updated.

**Comment by ajasnosz** [comment]
Hello @olgaktoronto, all mentioned mibs are now available in version 1.15.10. You can refer to [this](https://splunk.github.io/splunk-connect-for-snmp/main/mib-request/#update-your-instance-of-sc4snmp-with-the-newest-mib-server) instruction on how to set up new mibserver.

**Comment by olgaktoronto** [comment]
hi @ajasnosz  thank you SO MUCH!
